version: "3.9"
services:
  frontend:
    build:
      context: ..
      dockerfile: jenkins-pipeline/Dockerfile.frontend
    container_name: dev-frontend-container
    ports:
      - "3004:80"

  backend:
    build:
      context: ..
      dockerfile: jenkins-pipeline/Dockerfile.backend
    container_name: dev-backend-container
    ports:
      - "5004:5003"

  mongo:
    image: mongo:latest
    container_name: dev-mongo-container
    ports:
      - "27018:27017"
    volumes:
      - dev-mongo-data:/data/db

volumes:
  dev-mongo-data:
