version: "3.9"
services:
  frontend:
    build:
      context: ..
      dockerfile: jenkins-pipeline/Dockerfile.frontend
    container_name: dev-frontend-2   # <- unique name
    ports:
      - "3004:80"

  backend:
    build:
      context: ..
      dockerfile: jenkins-pipeline/Dockerfile.backend
    container_name: dev-backend-2    # <- unique name
    ports:
      - "5004:5003"

  mongo:
    image: mongo:latest
    container_name: dev-mongo-2      # <- unique name
    ports:
      - "27018:27017"
    volumes:
      - dev-mongo-data-2:/data/db

volumes:
  dev-mongo-data-2:
